version: '3'

services:
    loadbalancer:
        build:
            context: ./LBRoundRobin
            dockerfile: Dockerfile
        container_name: loadbalancer
        ports:
            - "35008:6000"
        depends_on:
            - logservice
    logservice:
        build:
            context: ./LogService
            dockerfile: Dockerfile
        ports:
            - "35001-35003:6000"
        depends_on:
            - db 
    db:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_INITDB_DATABASE=logservicedb
            - MONGO_INITDB_ROOT_USERNAME=angi
            - MONGO_INITDB_ROOT_PASSWORD=angi123
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo-volume:/data/db
        ports:
            - 27017:27017
        command: mongod
    